---
title: "Insanity"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: cerulean
    orientation: columns
    vertical_layout: fill
---

```{r setup, librarys, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(hrbrthemes)
library(ggthemes)
library(plotly)
library(calendR)
library(RColorBrewer)
```


```{r data, include=FALSE}
fit = read_csv("Fit Test.csv")
cal = read_csv("Calendar.csv")
```

```{r setup, include = FALSE}
thematic::thematic_rmd(font = "auto")
```

Fit Test
======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Fit Test Results

```{r}
fit_test = fit %>% 
  pivot_longer(cols = c(2:8), names_to = "Exercise", values_to = "Reps") %>% 
  ggplot(aes(y = Reps, x = `Test Number`, color = Exercise))+
  geom_line()+
  scale_y_continuous(labels = scales::number_format(accuracy = 1))+
  scale_x_continuous(breaks = seq(from = 1, to = max(fit$`Test Number`), by = 1))+
  facet_wrap(~fct_inorder(Exercise), scales = "free")+
  labs(title = "Fit Test Over Time")+
  theme_classic()+
  theme(legend.position = "NULL",
        plot.title = element_text(hjust = 0.5))
  
ggplotly(fit_test)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Weight

```{r}
weight = fit %>% ggplot(aes(x = `Test Number`, y = Weight))+
  geom_line()+
  scale_x_continuous(breaks = seq(from = 1, to = max(fit$`Test Number`), by = 1))+
  theme_classic()+
  labs(title = "Weight over time")+
  theme(plot.title = element_text(hjust = 0.5))

ggplotly(weight)
```

Data {data-width=1000, .tabset}
======================================================================
```{r}
DT::datatable(fit)
```

Calendar {data-width=1000, .tabset}
======================================================================

Row {.tabset}
----------------------------------------------------------------------

<!--
### August 2021
```{r eval=FALSE, include=FALSE, out.width="100%"}

uniq_event_aug = cal %>% 
  filter(Month=="August") %>% 
  select(Event) %>% 
  filter(!is.na(Event)==T) %>% 
  unique() %>% 
  pull() %>% 
  length()

pal_aug = RColorBrewer::brewer.pal(uniq_event_aug, name = "Spectral")

secondary = c(cal$Secondary[which(is.na(cal$Secondary)==F & cal$Month == "August")])
  
days = c(cal$Day[which(is.na(cal$Secondary)==F & cal$Month == "August")])

cale = calendR(year = 2021, month = 8,
        special.days = cal$Event[which(cal$Month=="August")],
        special.col = c(pal_aug[1:uniq_event_aug]), # as events
        low.col = "white",
        legend.pos = "bottom", # Legend position
        legend.title = "",
        day.size = 3,
        text.size = 3,
        text = secondary,
        text.pos = days,
        weeknames.size = 4)     # Legend title

ggplotly(cale) %>% layout(legend = list(orientation = "h",   # show entries horizontally
                     xanchor = "center",  # use center of legend as anchor
                     x = 0.5, y = 0))             # put legend in center of x-axis
```
-->

### July 2021
```{r, out.width="100%"}

uniq_event_jul = cal %>% 
  filter(Month=="July") %>% 
  select(Event) %>% 
  filter(!is.na(Event)==T) %>% 
  unique() %>% 
  pull() %>% 
  length()

pal_july = RColorBrewer::brewer.pal(uniq_event_jul, name = "Spectral")

secondary = c(cal$Secondary[which(is.na(cal$Secondary)==F & cal$Month == "July")])
  
days = c(cal$Day[which(is.na(cal$Secondary)==F & cal$Month == "July")])

cale = calendR(year = 2021, month = 7,
        special.days = cal$Event[which(cal$Month=="July")],
        special.col = c(pal_july[1:uniq_event_jul]), # as events
        low.col = "white",
        legend.pos = "bottom", # Legend position
        legend.title = "",
        day.size = 3,
        text.size = 3,
        text = secondary,
        text.pos = days,
        weeknames.size = 4)     # Legend title

ggplotly(cale) %>% layout(legend = list(orientation = "h",   # show entries horizontally
                     xanchor = "center",  # use center of legend as anchor
                     x = 0.5, y = 0))             # put legend in center of x-axis
```


### June 2021 
```{r, out.width="100%"}

uniq_event_jun = cal %>% 
  filter(Month=="June") %>% 
  select(Event) %>% 
  filter(!is.na(Event)==T) %>% 
  unique() %>% 
  pull() %>% 
  length()

pal_june = RColorBrewer::brewer.pal(uniq_event_jun, name = "Spectral")

secondary = c(cal$Secondary[which(is.na(cal$Secondary)==F & cal$Month == "June")])
  
days = c(cal$Day[which(is.na(cal$Secondary)==F & cal$Month == "June")])

cale = calendR(year = 2021, month = 6,
        special.days = cal$Event[which(cal$Month=="June")],
        special.col = c(pal_june[1:uniq_event_jun]), # as events
        low.col = "white",
        legend.pos = "bottom", # Legend position
        legend.title = "",
        day.size = 3,
        text.size = 3,
        text = secondary,
        text.pos = days,
        weeknames.size = 4)     # Legend title

ggplotly(cale) %>% layout(legend = list(orientation = "h",   # show entries horizontally
                     xanchor = "center",  # use center of legend as anchor
                     x = 0.5, y = 0))             # put legend in center of x-axis
```
